[package]
name = "avrman"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "avrman"
path = "src/avrman/main.rs"

[dependencies]
ihex = "3.0.0"
serialport = "4.7.1"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
